#!/bin/bash

#echo "Usage: dophyloP genename modTree species minAlignments DOPHYLOP"
GENENAME=$1
TREE=$2
SPECIES=$3
MINALIGNMENT=$4
DOPHYLOP=$5

if [ $5 == "DOPHYLOP" ]
then
	
##### Filter
	if [ -f $CONUNPE/../genes/${GENENAME}.maf ]
	then
		$CONUNPE/gene2genome $CONUNPE/gene2genome.dic $CONUNPE/../genes/${GENENAME}.maf  | grep -v '?' > $TMP/${GENENAME}.filter_tmp.maf
		$MAFFILTER/maffilter "input.file=${TMP}/${GENENAME}.filter_tmp.maf" "maf.filter=Concatenate(),MinBlockLength(min_length=8),Merge(species=($SPECIES), dist_max=4),EntropyFilter(species=($SPECIES)),MinBlockSize(min_size=$MINALIGNMENT),Output(file=$TMP/${GENENAME}.filter_tmp2.maf,compression=none)" >/dev/null 2>/dev/null
		filesize=$(stat -c%s "$TMP/${GENENAME}.filter_tmp2.maf")
		if (( filesize > 32 )); then
			$MAFTOOLS/bin/mafSorter --maf $TMP/${GENENAME}.filter_tmp2.maf --seq ${SPECIES}.c1 | sed 's/\.c1//' | $CONUNPE/fixMAF $SPECIES > $TMP/${GENENAME}.filter.maf
		fi
		rm $TMP/${GENENAME}.filter_tmp.maf
		rm $TMP/${GENENAME}.filter_tmp2.maf
	fi

	if [ -f $CONUNPE/../genes/${GENENAME}_down.maf ]
	then
		filesize=$(stat -c%s "$CONUNPE/../genes/${GENENAME}_down.maf")
		if (( filesize > 32 )); then
			$CONUNPE/gene2genome $CONUNPE/gene2genome.dic $CONUNPE/../genes/${GENENAME}_down.maf | grep -v '?' > $TMP/${GENENAME}_down.filter_tmp.maf
			$MAFFILTER/maffilter "input.file=${TMP}/${GENENAME}_down.filter_tmp.maf" "maf.filter=Concatenate(),MinBlockLength(min_length=8),Merge(species=($SPECIES), dist_max=4),EntropyFilter(species=($SPECIES)),MinBlockSize(min_size=$MINALIGNMENT),Output(file=$TMP/${GENENAME}_down.filter_tmp2.maf,compression=none)" >/dev/null 2>/dev/null
			filesize=$(stat -c%s "$TMP/${GENENAME}_down.filter_tmp2.maf")
			if (( filesize > 32 )); then	
				$MAFTOOLS/bin/mafSorter --maf $TMP/${GENENAME}_down.filter_tmp2.maf --seq ${SPECIES}.c1 | sed 's/\.c1//' | $CONUNPE/fixMAF $SPECIES > $TMP/${GENENAME}_down.filter.maf
			fi
			rm $TMP/${GENENAME}_down.filter_tmp.maf
			rm $TMP/${GENENAME}_down.filter_tmp2.maf
		fi
	fi

	genecoord=(`grep ${GENENAME} $CONUNPE/../allgenomes/$SPECIES.proce.genes.gff3 | awk '{print $1,$4,$5,$7}'`)
	dir=${genecoord[3]}
	ch=${genecoord[0]}
	start=${genecoord[1]}
	end=${genecoord[2]}


	if [ $dir == "-" ]
	then
		awkcmd="{print \"$ch\",($end+50000-\$3),($end+50000-\$2),\$5}"
		awkcmd_down="{print \"$ch\",($start-\$3),($start-\$2),\$5}"
	else 
		awkcmd="{print \"$ch\",($start-50000+\$2),($start-50000+\$3),\$5}"
		awkcmd_down="{print \"$ch\",($end+\$2),($end+\$3),\$5}"
	fi

	if [ -f $TMP/${GENENAME}.filter.maf ]
	then
		phyloP --seed 123 --wig-scores --no-prune --mode CON --method SCORE ${TREE} $TMP/${GENENAME}.filter.maf | wig2bed | sort -k1,1 -k2,2n | awk '{ if( $5 > 1 ) { print $0; } }' > $CONUNPE/../phyloP/CNS/${GENENAME}.phyloP.rel.bed
		#### This is for only parital conservation. prnue tree.
		#	phyloP --seed 123 --wig-scores            --mode CON --method SCORE ${TREE} $TMP/${GENENAME}.filter.maf | wig2bed | sort -k1,1 -k2,2n | awk '{ if( $5 > 1 ) { print $0; } }' > $CONUNPE/../phyloP/CNS/${GENENAME}.phyloP.rel.bed 
	
		cat $CONUNPE/../phyloP/CNS/${GENENAME}.phyloP.rel.bed | awk "BEGIN { OFS=\"\t\" } ${awkcmd}" | sort -k1,1 -k2,2n  >$CONUNPE/../phyloP/${GENENAME}.phyloP.bed
		#	cat $CONUNPE/../phyloP/CNS/${GENENAME}.phyloP.rel.bed | awk '{ if($2<49000) print;}' | awk "BEGIN { OFS=\"\t\" } ${awkcmd}" | sort -k1,1 -k2,2n  >$CONUNPE/../phyloP/justDistal/${GENENAME}.phyloP.bed
	
		awk '{ if($5>2) {print;}}' ${CONUNPE}/../phyloP/CNS/${GENENAME}.phyloP.rel.bed | bedtools merge -d 25 -c 5 -o mean | awk '{if(($3-$2)>=10) print; }' > ${CONUNPE}/../phyloP/CNS/${GENENAME}_CNS.bed

	fi

	if [ -f $TMP/${GENENAME}_down.filter.maf ]
	then
		phyloP --seed 123 --wig-scores --no-prune --mode CON --method SCORE ${TREE} $TMP/${GENENAME}_down.filter.maf | wig2bed | sort -k1,1 -k2,2n | awk '{ if( $5 > 1 ) { print $0; } }' | tee $CONUNPE/../phyloP/CNS/${GENENAME}_down.phyloP.rel.bed | awk "BEGIN { OFS=\"\t\" } ${awkcmd_down}" | sort -k1,1 -k2,2n >$CONUNPE/../phyloP/${GENENAME}_down.phyloP.bed  
		awk '{ if($5>2) {print;}}' ${CONUNPE}/../phyloP/CNS/${GENENAME}_down.phyloP.rel.bed | bedtools merge -d 25 -c 5 -o mean | awk '{if(($3-$2)>=10) print; }' > ${CONUNPE}/../phyloP/CNS/${GENENAME}_CNS_down.bed
	fi
  
	rm -f $TMP/${1}.filter.maf
	rm -f $TMP/${1}_down.filter.maf
fi

if [ $5 == "DONTDOPHYLOP" ]
then
	awk '{ if($5>2) {print;}}' ${CONUNPE}/../phyloP/CNS/${GENENAME}.phyloP.rel.bed | bedtools merge -d 25 -c 5 -o mean | awk '{if(($3-$2)>=10) print; }' > ${CONUNPE}/../phyloP/CNS/${GENENAME}_CNS.bed
fi

