#!/usr/bin/perl -w
use strict;


@ARGV or die "I need filename";

while (<>) {
  chomp;
  my ($ref,$start,$end,$score) = (split)[0,3,4,5];
   $start--; # zero-based, half-open
 # $score = 255 if $score !~ /^[-.Ee0-9]$/;

  print join("\t",$ref,$start,$end,$score), "\n";
}
