#!/usr/bin/perl
$|=1;

use strict;
use List::Util qw(min max);

if( @ARGV < 1) {
   print "makePromoterLengthDB <species>\n";
   exit();
}

my $CONUNPE=%ENV{CONUNPE};
my $species= $ARGV[0];

open (my $upstreamfile, $CONUNPE . "/../allgenomes/" . $species . ".upstream.fasta") || die "can`t open file upstream sequence file for $species";
open (my $downstreamfile, $CONUNPE . "/../allgenomes/" . $species . ".downstream.fasta") || die "can`t open file downstream sequence file for $species";

my %upstream_len;
my %downstream_len;

while(my $locus = <$upstreamfile>)
{
  chomp($locus);
  $locus = substr($locus,1);
  
  my $seq= <$upstreamfile>;
  my $countn = () = $seq =~ /N/g;
  
  $upstream_len{$locus}= length($seq) - $countn -1;

}
while(my $locus = <$downstreamfile>)
{
  chomp($locus);
  $locus = substr($locus,1);
  
  my $seq= <$downstreamfile>;
  my $countn = () = $seq =~ /N/g;
  $downstream_len{$locus}= (length($seq) - $countn) -1;
}

print "Locus,upstreamLength,downstreamLength\n";

foreach my $key (sort keys %upstream_len) {
	print $key . "," . %upstream_len{$key} . "," . %downstream_len{$key} . "\n";
}