#!/usr/bin/perl
use POSIX;
use strict;
use Getopt::Long;
use Cwd 'abs_path';
use threads;
use threads::shared;
my $threadlock:shared;

########### Parameters

my $upstreamLength;
my $downstreamLength;

###########

my $conservatoryDir=abs_path(".");
my $genome="";
my $family;
my $force=0;
my $verbose=0;
my $help=0;
my $genomeWasProcessed=0;
my $threads=16;

GetOptions ("conservatoryDirectory=s" => \$conservatoryDir,
			"family=s" => \$family,
			"threads=i" => \$threads,
			"force" => \$force,
			"verbose" => \$verbose,
			"help" => \$help) or die("Error in command line arguments\n");

			
if($help || $family eq "") {
	print "Conservatory version 0.0.1\n\n";
	
	print "processConservation --family <family>\n\n";
	print "\t--conservatoryDirectory\tPath of the main conservatory directory. See README for directory structure. (DEFAULT: current directory)\n";
	print "\t--family\t\tFamily for which to process conservation (MANDATORY).\n";
	print "\t--force\t\tForce rebuilding alignments.\n";
	print "\t--threads\t\tNumber of threads to use.\n";
	print "\t--verbose\t\tOutput extra progress messages.\n";
	print "\t--help\t\t\tPrints this message.\n\n";
	exit(0);
}

#################### Set up files
my $genomedb_file = "$conservatoryDir/genome_database.csv";
my $parameter_file = "$conservatoryDir/conservatory.parameters.txt";
my $outputDir = "$conservatoryDir/alignments/$family";
my $geneListFileName;

####### First, sanity checks. Check to see if blast is installed and if directory structure is OK.
####### 
die "ERROR: Cannot find file genome database file ($genomedb_file)\n" unless -e $genomedb_file;
die "ERROR: Cannot find file conservatory parameter file ($parameter_file)\n" unless -e $parameter_file;
die "ERROR: Conservatory directory structure at ($conservatoryDir) is corrupt\n" unless (-e "$conservatoryDir/genomes" && -e "$conservatoryDir/genomes/blastdb/" && -e "$conservatoryDir/scripts" && -e "$conservatoryDir/alignments");

my $bamtools = `sh -c 'command -v bamtools'`;
die "ERROR: Cannot find bamtools in path. Please make sure it is installed.\n" unless ($bamtools ne "");  

##################### Read Parameters
if($verbose) { print localtime(). ": Loading parameter file $parameter_file.\n"; }
open (my $parameters, "<", $parameter_file);
while(my $curline = <$parameters>) {
	chomp($curline);
	if(substr($curline,1,1) ne "#") {
		(my $paramName, my $paramValue) = split /=/, $curline;
		if(uc($paramName) eq "UPSTREAMLENGTH") { $upstreamLength = $paramValue; }
		elsif(uc($paramName) eq "DOWNSTREAMLENGTH") { $downstreamLength = $paramValue; }
		elsif($paramName ne "") { }
	}
}
close($parameters);
if($verbose) { print localtime() . ": Running parameters (upstreamLength $upstreamLength; downstreamLength $downstreamLength).\n"; } 

### Clear old locks
system("rm $outputDir/*.lock");

######## Read genome database file.
	
open(my $genomedb, "<", $genomedb_file);
my $header=<$genomedb>;
while(my $curgenomeline= <$genomedb>) {
	my ($curgenomeName, $curgenomeSpecies,  $curgenomeFamily, $curgenomeReference) = split /,/, $curgenomeline;
	
	if($family eq $curgenomeFamily && $curgenomeName eq $curgenomeReference) {
		$genomeWasProcessed=1;
		
		#### First, genome sanity check. See that we have all files.
		print localtime() . ": START processing conservation for $family (reference genome $curgenomeName)\n";
		$geneListFileName = "$conservatoryDir/genomes/$curgenomeName.orthologs.csv";
		die localtime() . ": ABORT Cannot find orthologs file ($geneListFileName). Was processGenomes run?\n" unless -e $geneListFileName;
		### Start threads
		my @alignmentThreads = map { threads->new(\&processAlignmentThread, $_) } 1 .. $threads;
		$_->join for @alignmentThreads;
		## Merge all BAM, sort and index
		unlink("$family.bam");
		system("ls *.bam > $family.bams.txt");
		system("bamtools merge -list $family.bams.txt -out $family.bam.tmp"); 
		system("samtools sort $family.bam.tmp > $family.bam");
		system("samtools index $family.bam");
		unlink("$family.bam.tmp");
		#remove all small bams ?
		#
		print localtime() . ": END processing conservation for $family (reference genome $curgenomeName)\n";
	}
}
close($genomedb);


if(! $genomeWasProcessed) { die ("ERROR: No family $family or no reference genome was found in $genomedb_file.\n"); }

print localtime() . ": END conservation processing run.\n";


sub processAlignmentThread {
	my $goodtogo=0;
	my ($threadnumber) = @_;
	print localtime() . ": OPEN thread $threadnumber.\n";
	my @locks;

	open(my $geneListFile, "<", $geneListFileName);
	while(my $geneline = <$geneListFile>) {
		my $curLocus;
		if (1) {
	   	  lock $threadlock;
	   	  ($curLocus) = split /,/,$geneline;
	   	  if(!( -e "$outputDir/$curLocus.lock")) {
			open(my $lock, ">","$outputDir/$curLocus.lock");
			close($lock);
			print localtime() . ": Thread $threadnumber is processing $curLocus.\n";
			push @locks, "$outputDir/$curLocus.lock";
			$goodtogo=1;
		  }
		}
		if($goodtogo) {
	   		my $alignmentParams = "--family $family --locus $curLocus --dump-bam";
	   		if($force) { $alignmentParams = "alignmentParams --force"; }
	   		system("$conservatoryDir/scripts/buildAlignmentForFamily $alignmentParams");
			$goodtogo=0;
		} 
	}
	#remove all locks.
	foreach my $lockToDelete (@locks) {
		unlink($lockToDelete);
	}

	close($geneListFile);
	print localtime() . ": CLOSE thread $threadnumber.\n";
}