#!/usr/bin/perl
use POSIX;
use strict;

my %dictionary;

my $inCDSFileName = $ARGV[0];
my $inDicFileName = $ARGV[1];

print STDERR "Processing $inCDSFileName with dictionary $inDicFileName...\n";

open (my $dicFile, $inDicFileName) || die ("Can't find dictionary file. \n");

while(my $curLine = <$dicFile>) {
	chomp $curLine;
	my ($from, $to) = split /,/,$curLine;
	
	$dictionary{$from}=$to;
}
close($dicFile);

open (my $cdsInFile , $inCDSFileName) || die ("Can't find CDS file. \n");
while(my $curLine = <$cdsInFile>) {
	chomp $curLine;
	if(substr($curLine,0,1) eq ">") {
		my $key = substr($curLine,1,length($curLine));
		$key =~ s/ .*$//;
		$key =~ s/\.[0-9]+$//;
	#	print $key . "\n";
		print ">" . $dictionary{$key} . "\n";
	} else {
		print "$curLine\n";
	}
}
close($cdsInFile);
