#!/usr/bin/perl

use POSIX;
use strict;

my $reference = $ARGV[0];
my $inblock=0;
my $blockLineCounter=0;
my $blockReferenceSp=0;
my @blockLines;

while(my $line = <STDIN>) {
	chomp($line);
	if(substr($line,0,1) eq "a") {
		if($inblock) {  ## DUMP BLOCK AND START a new one
			print $blockLines[0] . "\n";
			if($blockReferenceSp != 0) {
				print $blockLines[$blockReferenceSp] . "\n";
			}
			for(my $i =1; $i < $blockLineCounter; $i++) {
				if($i!=$blockReferenceSp) {
					print $blockLines[$i] ."\n";
				}
			}
			$blockLineCounter=0;
			$blockReferenceSp=0;
			$inblock=1;
			$blockLines[$blockLineCounter++] = $line;

		} else {
			$inblock=1;
			$blockLines[$blockLineCounter++] = $line;
		}
	} elsif(substr($line,0,1) eq "s") {
		if($line =~ /$reference/) {
			$blockReferenceSp = $blockLineCounter;
		}
		$blockLines[$blockLineCounter++] = $line;
	} else {
		print $line ."\n";
	}
}