#!/usr/bin/perl
use strict;
use warnings;

my %seq;
my $curname="";

open (my $infile, $ARGV[0]);

while(my $line=<$infile>) {
	chomp $line;
	
	if(substr($line,0,1) eq "s") {
		my $csvmafline = $line;
		$csvmafline=~ s/ +/,/g;
	#	print "$csvmafline\n";
		my @mafline =split /,/, $csvmafline;
		my $name = $mafline[1];
		$seq{$name} = "";
	}
}

seek($infile,0,0);

my $maxlen=0;

while(my $line = <$infile>) {
	chomp $line;
	
	if(substr($line,0,1) eq "#") {
	} elsif(substr($line,0,1) eq "a") {
		for my $sp (keys %seq) {
			if(length($seq{$sp}) != $maxlen) {
				$seq{$sp} .= '-' x ($maxlen - length($seq{$sp}));
			}
		}
	} elsif(substr($line,0,1) eq "s") {
			my $csvmafline = $line;
			$csvmafline=~ s/ +/,/g;
			my ($head, $name, $tmp1, $tmp2, $tmp3, $tmp4, $seq) = split /,/,$csvmafline;
			$seq{$name} .= $seq;
			$maxlen = length($seq{$name});
	}
}

for my $sp (keys %seq) {
	print ">$sp\n" . $seq{$sp} . "\n";
}